"""initial migration

Revision ID: 21855afbcdc4
Revises: 
Create Date: 2023-12-21 07:16:45.858871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21855afbcdc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('League',
    sa.Column('League_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('League_Name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('League_ID')
    )
    op.create_table('Club',
    sa.Column('Club_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Club_Name', sa.String(length=50), nullable=True),
    sa.Column('Wins', sa.Integer(), nullable=True),
    sa.Column('Loses', sa.Integer(), nullable=True),
    sa.Column('Draws', sa.Integer(), nullable=True),
    sa.Column('League_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['League_ID'], ['League.League_ID'], ),
    sa.PrimaryKeyConstraint('Club_ID')
    )
    op.create_table('Game',
    sa.Column('Match_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Club1_Name', sa.String(length=50), nullable=True),
    sa.Column('Club2_Name', sa.String(length=50), nullable=True),
    sa.Column('History', sa.Date(), nullable=True),
    sa.Column('Stadium', sa.String(length=50), nullable=True),
    sa.Column('Players_Assists', sa.Integer(), nullable=True),
    sa.Column('Players_Goals', sa.Integer(), nullable=True),
    sa.Column('Team1_Scores', sa.Integer(), nullable=True),
    sa.Column('Team2_Scores', sa.Integer(), nullable=True),
    sa.Column('League_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['League_ID'], ['League.League_ID'], ),
    sa.PrimaryKeyConstraint('Match_ID')
    )
    op.create_table('Play_Match',
    sa.Column('Club1_ID', sa.Integer(), nullable=False),
    sa.Column('Club2_ID', sa.Integer(), nullable=False),
    sa.Column('Match_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Club1_ID'], ['Club.Club_ID'], ),
    sa.ForeignKeyConstraint(['Club2_ID'], ['Club.Club_ID'], ),
    sa.ForeignKeyConstraint(['Match_ID'], ['Game.Match_ID'], ),
    sa.PrimaryKeyConstraint('Club1_ID', 'Club2_ID', 'Match_ID')
    )
    op.create_table('Player',
    sa.Column('Player_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Player_Name', sa.String(length=50), nullable=True),
    sa.Column('Position', sa.String(length=50), nullable=True),
    sa.Column('Goals', sa.Integer(), nullable=True),
    sa.Column('Asists', sa.Integer(), nullable=True),
    sa.Column('Club_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Club_ID'], ['Club.Club_ID'], ),
    sa.PrimaryKeyConstraint('Player_ID')
    )
    op.create_table('Match_Result_Assist',
    sa.Column('Match_ID', sa.Integer(), nullable=False),
    sa.Column('Player_ID', sa.Integer(), nullable=False),
    sa.Column('Player_Num_Asists', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Match_ID'], ['Game.Match_ID'], ),
    sa.ForeignKeyConstraint(['Player_ID'], ['Player.Player_ID'], ),
    sa.PrimaryKeyConstraint('Match_ID', 'Player_ID')
    )
    op.create_table('Match_Result_Score',
    sa.Column('Match_ID', sa.Integer(), nullable=False),
    sa.Column('Player_ID', sa.Integer(), nullable=False),
    sa.Column('Player_Num_Goals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Match_ID'], ['Game.Match_ID'], ),
    sa.ForeignKeyConstraint(['Player_ID'], ['Player.Player_ID'], ),
    sa.PrimaryKeyConstraint('Match_ID', 'Player_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Match_Result_Score')
    op.drop_table('Match_Result_Assist')
    op.drop_table('Player')
    op.drop_table('Play_Match')
    op.drop_table('Game')
    op.drop_table('Club')
    op.drop_table('League')
    # ### end Alembic commands ###
